//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathwayService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", ConfigurationName="PathwayService.PathWayServiceSoap")]
    public interface PathWayServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/ServiceDetailsById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PathwayService.ServiceDetailsByIdResponse> ServiceDetailsByIdAsync(PathwayService.ServiceDetailsByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/GetHospitalScores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PathwayService.GetHospitalScoresResponse> GetHospitalScoresAsync(PathwayService.GetHospitalScoresRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://nww.pathwaysdos.nhs.uk/app/api/webservices/CheckCapacitySummary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PathwayService.CheckCapacitySummaryResponse> CheckCapacitySummaryAsync(PathwayService.CheckCapacitySummaryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class UserInfo
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class AgeRange
    {
        
        private float daysFromField;
        
        private float daysToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float daysFrom
        {
            get
            {
                return this.daysFromField;
            }
            set
            {
                this.daysFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float daysTo
        {
            get
            {
                return this.daysToField;
            }
            set
            {
                this.daysToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class Attribute
    {
        
        private string dataTypeField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dataType
        {
            get
            {
                return this.dataTypeField;
            }
            set
            {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class TimeOfDay
    {
        
        private short hoursField;
        
        private short minutesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public short hours
        {
            get
            {
                return this.hoursField;
            }
            set
            {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short minutes
        {
            get
            {
                return this.minutesField;
            }
            set
            {
                this.minutesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceCareItemRotaSession
    {
        
        private DayOfWeek startDayOfWeekField;
        
        private TimeOfDay startTimeField;
        
        private DayOfWeek endDayOfWeekField;
        
        private TimeOfDay endTimeField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DayOfWeek startDayOfWeek
        {
            get
            {
                return this.startDayOfWeekField;
            }
            set
            {
                this.startDayOfWeekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TimeOfDay startTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DayOfWeek endDayOfWeek
        {
            get
            {
                return this.endDayOfWeekField;
            }
            set
            {
                this.endDayOfWeekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TimeOfDay endTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum DayOfWeek
    {
        
        /// <remarks/>
        Sunday,
        
        /// <remarks/>
        Monday,
        
        /// <remarks/>
        Tuesday,
        
        /// <remarks/>
        Wednesday,
        
        /// <remarks/>
        Thursday,
        
        /// <remarks/>
        Friday,
        
        /// <remarks/>
        Saturday,
        
        /// <remarks/>
        Bankholiday,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class CapacityAttribute
    {
        
        private string nameField;
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceType
    {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceCareSummaryDestination
    {
        
        private int idField;
        
        private Capacity capacityField;
        
        private string nameField;
        
        private string publicNameField;
        
        private string contactDetailsField;
        
        private string addressField;
        
        private string postcodeField;
        
        private int northingsField;
        
        private bool northingsFieldSpecified;
        
        private int eastingsField;
        
        private bool eastingsFieldSpecified;
        
        private string urlField;
        
        private ServiceType serviceTypeField;
        
        private string odsCodeField;
        
        private string nonPublicTelephoneNoField;
        
        private string faxField;
        
        private string publicFacingInformationField;
        
        private string distanceField;
        
        private string referralInformationField;
        
        private bool openAllHoursField;
        
        private CapacityAttribute[] capacityAttributesField;
        
        private Endpoint[] serviceEndpointsField;
        
        private ServiceCareItemRotaSession[] rotaSessionsField;
        
        private string[] openTimeSpecifiedSessionsField;
        
        private Attribute[] attributesField;
        
        private AgeRange[] serviceAgeRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Capacity capacity
        {
            get
            {
                return this.capacityField;
            }
            set
            {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string publicName
        {
            get
            {
                return this.publicNameField;
            }
            set
            {
                this.publicNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string contactDetails
        {
            get
            {
                return this.contactDetailsField;
            }
            set
            {
                this.contactDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int northings
        {
            get
            {
                return this.northingsField;
            }
            set
            {
                this.northingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool northingsSpecified
        {
            get
            {
                return this.northingsFieldSpecified;
            }
            set
            {
                this.northingsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int eastings
        {
            get
            {
                return this.eastingsField;
            }
            set
            {
                this.eastingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eastingsSpecified
        {
            get
            {
                return this.eastingsFieldSpecified;
            }
            set
            {
                this.eastingsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public ServiceType serviceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string odsCode
        {
            get
            {
                return this.odsCodeField;
            }
            set
            {
                this.odsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string nonPublicTelephoneNo
        {
            get
            {
                return this.nonPublicTelephoneNoField;
            }
            set
            {
                this.nonPublicTelephoneNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string publicFacingInformation
        {
            get
            {
                return this.publicFacingInformationField;
            }
            set
            {
                this.publicFacingInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string referralInformation
        {
            get
            {
                return this.referralInformationField;
            }
            set
            {
                this.referralInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool openAllHours
        {
            get
            {
                return this.openAllHoursField;
            }
            set
            {
                this.openAllHoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute("capacityAttribute")]
        public CapacityAttribute[] capacityAttributes
        {
            get
            {
                return this.capacityAttributesField;
            }
            set
            {
                this.capacityAttributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        [System.Xml.Serialization.XmlArrayItemAttribute("endpoint")]
        public Endpoint[] serviceEndpoints
        {
            get
            {
                return this.serviceEndpointsField;
            }
            set
            {
                this.serviceEndpointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceCareItemRotaSession")]
        public ServiceCareItemRotaSession[] rotaSessions
        {
            get
            {
                return this.rotaSessionsField;
            }
            set
            {
                this.rotaSessionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=21)]
        [System.Xml.Serialization.XmlArrayItemAttribute("openTimeSpecified")]
        public string[] openTimeSpecifiedSessions
        {
            get
            {
                return this.openTimeSpecifiedSessionsField;
            }
            set
            {
                this.openTimeSpecifiedSessionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=22)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attribute")]
        public Attribute[] attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=23)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ageRange")]
        public AgeRange[] serviceAgeRange
        {
            get
            {
                return this.serviceAgeRangeField;
            }
            set
            {
                this.serviceAgeRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum Capacity
    {
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class Endpoint
    {
        
        private int endpointOrderField;
        
        private string transportField;
        
        private string formatField;
        
        private string interactionField;
        
        private string businessScenarioField;
        
        private string addressField;
        
        private string compressionField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int endpointOrder
        {
            get
            {
                return this.endpointOrderField;
            }
            set
            {
                this.endpointOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string transport
        {
            get
            {
                return this.transportField;
            }
            set
            {
                this.transportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string interaction
        {
            get
            {
                return this.interactionField;
            }
            set
            {
                this.interactionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string businessScenario
        {
            get
            {
                return this.businessScenarioField;
            }
            set
            {
                this.businessScenarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string compression
        {
            get
            {
                return this.compressionField;
            }
            set
            {
                this.compressionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class Case
    {
        
        private string caseRefField;
        
        private string caseIdField;
        
        private string postcodeField;
        
        private string surgeryField;
        
        private short ageField;
        
        private AgeFormatType ageFormatField;
        
        private int dispositionField;
        
        private int symptomGroupField;
        
        private int[] symptomDiscriminatorListField;
        
        private int searchDistanceField;
        
        private bool searchDistanceFieldSpecified;
        
        private bool forceSearchDistanceField;
        
        private GenderType genderField;
        
        private string searchDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string caseRef
        {
            get
            {
                return this.caseRefField;
            }
            set
            {
                this.caseRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string caseId
        {
            get
            {
                return this.caseIdField;
            }
            set
            {
                this.caseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string surgery
        {
            get
            {
                return this.surgeryField;
            }
            set
            {
                this.surgeryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public short age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AgeFormatType ageFormat
        {
            get
            {
                return this.ageFormatField;
            }
            set
            {
                this.ageFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int disposition
        {
            get
            {
                return this.dispositionField;
            }
            set
            {
                this.dispositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int symptomGroup
        {
            get
            {
                return this.symptomGroupField;
            }
            set
            {
                this.symptomGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public int[] symptomDiscriminatorList
        {
            get
            {
                return this.symptomDiscriminatorListField;
            }
            set
            {
                this.symptomDiscriminatorListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int searchDistance
        {
            get
            {
                return this.searchDistanceField;
            }
            set
            {
                this.searchDistanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchDistanceSpecified
        {
            get
            {
                return this.searchDistanceFieldSpecified;
            }
            set
            {
                this.searchDistanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool forceSearchDistance
        {
            get
            {
                return this.forceSearchDistanceField;
            }
            set
            {
                this.forceSearchDistanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public GenderType gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string searchDateTime
        {
            get
            {
                return this.searchDateTimeField;
            }
            set
            {
                this.searchDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum AgeFormatType
    {
        
        /// <remarks/>
        Days,
        
        /// <remarks/>
        Months,
        
        /// <remarks/>
        Years,
        
        /// <remarks/>
        AgeGroup,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum GenderType
    {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        I,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class Hospital
    {
        
        private string hospital_nameField;
        
        private int total_scoreField;
        
        private string noteField;
        
        private string update_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string hospital_name
        {
            get
            {
                return this.hospital_nameField;
            }
            set
            {
                this.hospital_nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int total_score
        {
            get
            {
                return this.total_scoreField;
            }
            set
            {
                this.total_scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string update_date
        {
            get
            {
                return this.update_dateField;
            }
            set
            {
                this.update_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public partial class ServiceDetail
    {
        
        private string idField;
        
        private string odsCodeField;
        
        private Endpoint[] serviceEndpointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string odsCode
        {
            get
            {
                return this.odsCodeField;
            }
            set
            {
                this.odsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("endpoint")]
        public Endpoint[] serviceEndpoints
        {
            get
            {
                return this.serviceEndpointsField;
            }
            set
            {
                this.serviceEndpointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceDetailsById", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ServiceDetailsByIdRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public PathwayService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=1)]
        public string serviceId;
        
        public ServiceDetailsByIdRequest()
        {
        }
        
        public ServiceDetailsByIdRequest(string serviceVersion, PathwayService.UserInfo userInfo, string serviceId)
        {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
            this.serviceId = serviceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceDetailsByIdResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class ServiceDetailsByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public PathwayService.ServiceDetail[] services;
        
        public ServiceDetailsByIdResponse()
        {
        }
        
        public ServiceDetailsByIdResponse(PathwayService.ServiceDetail[] services)
        {
            this.services = services;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHospitalScores", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class GetHospitalScoresRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public PathwayService.UserInfo userInfo;
        
        public GetHospitalScoresRequest()
        {
        }
        
        public GetHospitalScoresRequest(string serviceVersion, PathwayService.UserInfo userInfo)
        {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetHospitalScoresResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class GetHospitalScoresResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public PathwayService.Hospital[] GetHospitalScoresResult;
        
        public GetHospitalScoresResponse()
        {
        }
        
        public GetHospitalScoresResponse(PathwayService.Hospital[] GetHospitalScoresResult)
        {
            this.GetHospitalScoresResult = GetHospitalScoresResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
    public enum DistanceSource
    {
        
        /// <remarks/>
        Postcode,
        
        /// <remarks/>
        District,
        
        /// <remarks/>
        Sector,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Web Service")]
        WebService,
        
        /// <remarks/>
        National,
        
        /// <remarks/>
        Override,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCapacitySummary", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class CheckCapacitySummaryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices")]
        public string serviceVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public PathwayService.UserInfo userInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=1)]
        public PathwayService.Case c;
        
        public CheckCapacitySummaryRequest()
        {
        }
        
        public CheckCapacitySummaryRequest(string serviceVersion, PathwayService.UserInfo userInfo, PathwayService.Case c)
        {
            this.serviceVersion = serviceVersion;
            this.userInfo = userInfo;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckCapacitySummaryResponse", WrapperNamespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", IsWrapped=true)]
    public partial class CheckCapacitySummaryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=0)]
        public string TransactionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=1)]
        public string RequestedAtDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=2)]
        public string SearchDateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=3)]
        public float CalculatedAgeInDays;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=4)]
        public int SearchDistance;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=5)]
        public PathwayService.DistanceSource SearchDistanceUsedSource;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://nww.pathwaysdos.nhs.uk/app/api/webservices", Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceCareSummaryDestination")]
        public PathwayService.ServiceCareSummaryDestination[] CheckCapacitySummaryResult;
        
        public CheckCapacitySummaryResponse()
        {
        }
        
        public CheckCapacitySummaryResponse(string TransactionId, string RequestedAtDateTime, string SearchDateTime, float CalculatedAgeInDays, int SearchDistance, PathwayService.DistanceSource SearchDistanceUsedSource, PathwayService.ServiceCareSummaryDestination[] CheckCapacitySummaryResult)
        {
            this.TransactionId = TransactionId;
            this.RequestedAtDateTime = RequestedAtDateTime;
            this.SearchDateTime = SearchDateTime;
            this.CalculatedAgeInDays = CalculatedAgeInDays;
            this.SearchDistance = SearchDistance;
            this.SearchDistanceUsedSource = SearchDistanceUsedSource;
            this.CheckCapacitySummaryResult = CheckCapacitySummaryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface PathWayServiceSoapChannel : PathwayService.PathWayServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class PathWayServiceSoapClient : System.ServiceModel.ClientBase<PathwayService.PathWayServiceSoap>, PathwayService.PathWayServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PathWayServiceSoapClient() : 
                base(PathWayServiceSoapClient.GetDefaultBinding(), PathWayServiceSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PathWayServiceSoap12.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PathWayServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PathWayServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), PathWayServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PathWayServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PathWayServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PathWayServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PathWayServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PathWayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PathwayService.ServiceDetailsByIdResponse> PathwayService.PathWayServiceSoap.ServiceDetailsByIdAsync(PathwayService.ServiceDetailsByIdRequest request)
        {
            return base.Channel.ServiceDetailsByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<PathwayService.ServiceDetailsByIdResponse> ServiceDetailsByIdAsync(string serviceVersion, PathwayService.UserInfo userInfo, string serviceId)
        {
            PathwayService.ServiceDetailsByIdRequest inValue = new PathwayService.ServiceDetailsByIdRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            inValue.serviceId = serviceId;
            return ((PathwayService.PathWayServiceSoap)(this)).ServiceDetailsByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PathwayService.GetHospitalScoresResponse> PathwayService.PathWayServiceSoap.GetHospitalScoresAsync(PathwayService.GetHospitalScoresRequest request)
        {
            return base.Channel.GetHospitalScoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<PathwayService.GetHospitalScoresResponse> GetHospitalScoresAsync(string serviceVersion, PathwayService.UserInfo userInfo)
        {
            PathwayService.GetHospitalScoresRequest inValue = new PathwayService.GetHospitalScoresRequest();
            inValue.serviceVersion = serviceVersion;
            inValue.userInfo = userInfo;
            return ((PathwayService.PathWayServiceSoap)(this)).GetHospitalScoresAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<PathwayService.CheckCapacitySummaryResponse> CheckCapacitySummaryAsync(PathwayService.CheckCapacitySummaryRequest request)
        {
            return base.Channel.CheckCapacitySummaryAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PathWayServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PathWayServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://nww.pathwaysdos.nhs.uk/app/api/webservices");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PathWayServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.PathWayServiceSoap12);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PathWayServiceSoapClient.GetEndpointAddress(EndpointConfiguration.PathWayServiceSoap12);
        }
        
        public enum EndpointConfiguration
        {
            
            PathWayServiceSoap12,
        }
    }
}
